apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: gostrategy-postgres
    url: gostrategy:5432
    user: ${DB_USER}
    secureJsonData:
      password: ${DB_PASSWORD}
    jsonData:
      database: ${DB_NAME}
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    isDefault: false

  - name: Prometheus
    type: prometheus
    uid: gostrategy-prometheus
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      httpMethod: POST
      timeInterval: 15s

  - name: Loki
    type: loki
    uid: gostrategy-loki
    url: http://loki:3100
    isDefault: false
    jsonData:
      maxLines: 1000
